name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Build extension
      run: npm run build
    
    - name: Zip extension
      run: |
        cd dist
        zip -r ../online-ide-opener.zip *
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: online-ide-opener.zip
        draft: false
        prerelease: false
        generate_release_notes: true
